#pragma kernel InvertColorTone
#pragma kernel SepiaTone
#pragma kernel SaturateTone

Texture2D<float4> SourceTexture;
SamplerState sampler_SourceTexture;

RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void InvertColorTone (uint3 id : SV_DispatchThreadID)
{

    uint dimension_x;
    uint dimension_y;
    SourceTexture.GetDimensions(dimension_x, dimension_y);
    
    float2 uv = float2(id.xy/float2(dimension_x, dimension_y));

    float4 color = SourceTexture.SampleLevel(sampler_SourceTexture, uv, 0);
    color.rgb = 1.0 - color.rgb; // Invert the RGB channels
    
    Result[id.xy] =  color;
}

[numthreads(8,8,1)]
void SepiaTone (uint3 id : SV_DispatchThreadID)
{
    uint dimension_x;
    uint dimension_y;
    SourceTexture.GetDimensions(dimension_x, dimension_y);
    
    float2 uv = float2(id.xy/float2(dimension_x, dimension_y));

    float4 color = SourceTexture.SampleLevel(sampler_SourceTexture, uv, 0);
    
    // Apply sepia tone effect
    float r = dot(color.rgb, float3(0.393, 0.769, 0.189));
    float g = dot(color.rgb, float3(0.349, 0.686, 0.168));
    float b = dot(color.rgb, float3(0.272, 0.534, 0.131));
    
    Result[id.xy] = float4(r, g, b, color.a);
}

[numthreads(8,8,1)]
void SaturateTone(uint3 id : SV_DispatchThreadID)
{
    uint dimension_x;
    uint dimension_y;
    SourceTexture.GetDimensions(dimension_x, dimension_y);
    
    float2 uv = float2(id.xy/float2(dimension_x, dimension_y));

    float4 color = SourceTexture.SampleLevel(sampler_SourceTexture, uv, 0);
    
    // Apply saturation effect
    float gray = dot(color.rgb, float3(0.299, 0.587, 0.114));
    color.rgb = lerp(float3(gray, gray, gray), color.rgb, 1.5); // Increase saturation
    
    Result[id.xy] = color;
}