// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> _SourceTex;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint2 texSize = uint2(0,0);
    _SourceTex.GetDimensions(texSize.x, texSize.y);
    _SourceTex.Load()
    uint2 uv = id.xy / texSize.xy;

    _SourceTex.
    
}
